wallpaper {
    monitor = eDP-2
    path = ~/.config/wallpapers/wall11.jpg
    fit_mode = cover
}

wallpaper {
    monitor = eDP-1
    path = ~/.config/wallpapers/wall11.jpg
    fit_mode = cover
}

ipc = false
splash = false
